### PR TITLE
Match `<head>` but not `<header>` in add-script

### LINKED ISSUE #9: Two scripts added when response body includes both `<head>` and `<header>` tags
## Expected
One script added to the response body, when it includes both `<head>` and `<header>` tags.

## Actual
Two scripts added to the response body.

## Steps to Reproduce
1. Run a task using ring-refresh in a project
2. Return a response body with both `<head>` and `<header>` tags
   ```html
   <html>
   <head>
     <title>Title</title>
   </head>
   <body>
     <header>This is a header</header>
   </body>
   </html>
   ```
3. Observe the script being added to the response body twice, in the `<head>` and `<header>` tags

## Versions
Ring-Refresh 0.1.2 (lein-ring 0.12.6 -> lein-server 0.5.0 -> ring-refresh 0.1.2)
Clojure 1.11.0
Java 11.0.14
Leiningen 2.9.8

## More Info
The [regex in refresh/add-script](https://github.com/weavejester/ring-refresh/blob/9115d8510808b9c83f9fa3296043527b4c78094e/src/ring/middleware/refresh.clj#L41) is a bit greedy: `#"<head\s*[^>]*>"`

**Fix:** Replacing it with `@"<head(?!er)\s*[^\/>]*>"` seems to accommodate the different scenarios.

PR incoming.

### PR DESCRIPTION
**Pull request by stevejmp**
Fixes #9

Added tests in 20975cd for a baseline. The first `testing` set passes, and the second set fails. Running the tests with `lein test` requires temporarily bumping Clojure to `1.7.0` or later.

Updated the regex in 2e991ad. All tests pass.

### CODE REVIEW

**Comment by weavejester** [comment]
What about: `#"<head(\s+[^>]*|)>"` instead? That way it's not dependent on looking for "er".

Can you ensure that any line is within 80 characters? This repo is old enough not to have contributing guidelines added to it, but I have some [guidelines](https://github.com/weavejester/contributing/blob/master/CONTRIBUTING.md) written up in a separate repository that should help.

**Comment by stevejmp** [comment]
> I have some [guidelines](https://github.com/weavejester/contributing/blob/master/CONTRIBUTING.md) written up in a separate repository that should help.

I haven't read the seven rules in a while, re-reading more often is going to help me stay consistent. Bookmarked. Cheers!

> Can you ensure that any line is within 80 characters?

Done. I usually stick to 80 as well, but I somehow thought that this was a good exception. As it turns out, breaking the lines right after the script tags actually makes it easier to see exactly where the script is injected at a glance. Great call, once again.

> What about: `#"<head(\s+[^>]*|)>"` instead? That way it's not dependent on looking for "er".

This specific regex breaks, unfortunately.

I had it looking for "er" because there are exactly two tags in html5 that begin with `head`, and those are `<head>` and `<header>`. My hope was that the proposed regex, `#"<head(?!er)\s*[^\/>]*>"`, conveys the intent to cover these two cases.

If you still prefer to remove the "er", I'll work on it and make another commit. Please let me know.

**Comment by weavejester** [comment]
Try `#"<head(?:\s+[^\/>]*|\s*)>"`, then. It's better to whitelist than to blacklist. If the HTML spec changes and introduces another `head*` element, it's better to be future proof.

The tests should also not reference a private function, as that's not part of the public API. Instead, it's better to create a helper function to setup testing the handler output directly.

**Comment by weavejester** [comment]
`#"<head\s*(?:\s[^\/>]+)?>"` should also work and might be a little better.

**Comment by stevejmp** [comment]
> `#"<head\s*(?:\s[^\/>]+)?>"` should also work and might be a little better.

This worked great. Cheers!

> The tests should also not reference a private function, as that's not part of the public API.

The tests now use the public API, and are using the minimum amount of data required in the request and response to pass.

Note that there is a somewhat bulky repetition (twice) in the `are` template expressions:

```clj
        (= result-body (-> (create-success-html-handler body)
                           sut/wrap-refresh
                           invoke-with-get-request
                           :body))
```

Failing tests often output the result of macro expansion to assist the user in debugging. I think if we obfuscate more of what's going on behind a function call, it will make it harder to debug failing tests later. If you still prefer extracting it all to a function, I can do that. Please let me know.

**Comment by weavejester** [comment]
I think I'd still favour extracting it into a function.

File: test/ring/middleware/test/refresh.clj [hunk 1]
```diff
@@ -1,6 +1,88 @@
 (ns ring.middleware.test.refresh
-  (:use clojure.test
-        ring.middleware.refresh))
+  (:require
```
Comment (weavejester) [inline test/ring/middleware/test/refresh.clj]: Can you format this as:

```clojure
(:require [clojure.java.io :as io]
          [clojure.test :refer [are deftest testing]]
          [ring.middleware.refresh :refer :all])
```

File: test/ring/middleware/test/refresh.clj [hunk 2]
```diff
@@ -1,6 +1,88 @@
...
+   [clojure.java.io :as io]
+   [clojure.test :refer [are deftest testing]]
+   [ring.middleware.refresh :as sut]))
 
-(deftest test-wrap-refresh
-  (is (true? false)))
\ No newline at end of file
+(defn create-success-html-handler [body]
```
Comment (weavejester) [inline test/ring/middleware/test/refresh.clj]: Can you make this function private?

File: test/ring/middleware/test/refresh.clj [hunk 3]
```diff
@@ -1,6 +1,88 @@
...
+  (constantly {:body body, :headers {"Content-Type" "text/html"}, :status 200}))
```
Comment (weavejester) [inline test/ring/middleware/test/refresh.clj]: Can you swap the positions of `:status 200` and `:body body`? As a convention, I tend to order them in the order they appear in a HTTP request.

Comment (weavejester) [reply test/ring/middleware/test/refresh.clj]: This could also be written as:

```clojure
(defn- create-test-handler [body]
  (-> (constantly {:status 200
                   :headers {"Content-Type" "text/html"}
                   :body body})
      (wrap-refresh))
```

As I don't think we'd ever need a handler without the middleware we're testing attached.

File: test/ring/middleware/test/refresh.clj [hunk 4]
```diff
@@ -1,6 +1,88 @@
...
+
+(defn invoke-with-get-request [handler]
```
Comment (weavejester) [inline test/ring/middleware/test/refresh.clj]: Maybe:

```clojure
(defn- get-test-response-body [handler]
  (:body (handler {:request-method :get, :uri "/"})))
```

Again, the reasoning is that we don't need anything except the body.

File: test/ring/middleware/test/refresh.clj [hunk 5]
```diff
@@ -1,6 +1,88 @@
...
+        (str "<html><head>"
+             "</head><body>body</body></html>")
+
+        (str "<html><head>"
+             "<script type=\"text/javascript\">" refresh-script "</script>"
+             "<title>title</title></head><body>body</body></html>")
+        (str "<html><head>"
+             "<title>title</title></head><body>body</body></html>")
+
+        (str
```
Comment (weavejester) [inline test/ring/middleware/test/refresh.clj:46]: Should follow style guidelines, so:

```clojure
(str x
     y
     z)
```

Or:

```clojure
(str
 x
 y
 z)
```

**Review by weavejester — CHANGES_REQUESTED** [review]

File: test/ring/middleware/test/refresh.clj (hunk 1 above)
Comment (stevejmp) [reply test/ring/middleware/test/refresh.clj]: Done.

File: test/ring/middleware/test/refresh.clj (hunk 2 above)
Comment (stevejmp) [reply test/ring/middleware/test/refresh.clj]: Done.

File: test/ring/middleware/test/refresh.clj (hunk 3 above)
Comment (stevejmp) [reply test/ring/middleware/test/refresh.clj]: Done. I didn't use parens around the arg-less `wrap-refresh` function call. If you prefer these, I can certainly add them.

File: test/ring/middleware/test/refresh.clj (hunk 4 above)
Comment (stevejmp) [reply test/ring/middleware/test/refresh.clj]: Done.

File: test/ring/middleware/test/refresh.clj (hunk 5 above)
Comment (stevejmp) [reply test/ring/middleware/test/refresh.clj:46]: Great catch. Done.

**Comment by stevejmp** [comment]
New commit pushed.

I have a couple of questions, if you don't mind:
1. Should we rename the `are` args? Perhaps using the word, "expected"?
2. Is the `ring.middleware.test.*` namespace a convention you're currently using? Some tooling defaults to finding test vars for `my.namespace` in `my.namespace-test`, to run tests in the REPL from the source file.

**Comment by stevejmp** [comment]
In case a notification was missed, awaiting feedback on the last commit of this PR.

**Comment by weavejester** [comment]
> 1. Should we rename the `are` args? Perhaps using the word, "expected"?

Sure, could be `expected-body` and `actual-body`, though I don't think there's any problem with the current names.

> 2. Is the `ring.middleware.test.*` namespace a convention you're currently using? Some tooling defaults to finding test vars for `my.namespace` in `my.namespace-test`, to run tests in the REPL from the source file.

It was Leiningen's default when the project was made, and it's since changed. I'm fine with changing it to `my.namespace-test` format, though in another PR.

> In case a notification was missed, awaiting feedback on the last commit of this PR.

Sorry about that; it all looks okay, just needs to be squashed.

**Comment by stevejmp** [comment]
> it all looks okay, just needs to be squashed.

Done. Please let me know if anything more is needed.

**Comment by weavejester** [comment]
Thanks! Can you change the commit message to:

    Improve regex matching head tag (fixes #9)

**Comment by stevejmp** [comment]
> Can you change the commit message

Done.
